// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ohjhzmqcbprcybjlsusp.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oamh6bXFjYnByY3liamxzdXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMzcwNjYsImV4cCI6MjA4NTcxMzA2Nn0.Uxfwf5-BSJ9EbFRp5MsfFr1zHvEGYGj3hLGtpPiDEck";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
