// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ohjhzmqcbprcybjlsusp.supabase.co";
const VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ecIjomNewTs7vYY1IWCD9Q_Ba9e6M6-";

export const supabase = createClient<Database>(SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
// TEMP DEBUG – remove later
// @ts-ignore
window.supabase = supabase;
